#!/usr/bin/env python
# encoding: utf-8

"""
Simple wrapper that runs the main pipless module
"""


import imp
import __main__

_,pipless_path,_ = imp.find_module("pipless")

globals_ = globals()
globals_.update(dict(
    __name__ = "__main__",
    __file__ = pipless_path
))

execfile(pipless_path, globals_)
